CREATE TABLE projects (
                          id VARCHAR(36) NOT NULL,
                          archived_at DATETIME(6) DEFAULT NULL,
                          archived_by VARCHAR(36) DEFAULT NULL,
                          color VARCHAR(7) DEFAULT NULL,
                          completed_at DATETIME(6) DEFAULT NULL,
                          completed_task_count INT DEFAULT NULL,
                          cover_url VARCHAR(255) DEFAULT NULL,
                          created_at DATETIME(6) DEFAULT NULL,
                          created_by VARCHAR(36) NOT NULL,
                          is_deleted BIT(1) DEFAULT NULL,
                          deleted_at DATETIME(6) DEFAULT NULL,
                          deleted_by VARCHAR(36) DEFAULT NULL,
                          description TEXT,
                          due_date DATETIME(6) DEFAULT NULL,
                          icon_url VARCHAR(255) DEFAULT NULL,
                          member_count INT DEFAULT NULL,
                          name VARCHAR(100) NOT NULL,
                          org_id VARCHAR(36) NOT NULL,
                          owned_by VARCHAR(36) NOT NULL,
                          is_pinned BIT(1) DEFAULT NULL,
                          slug VARCHAR(120) NOT NULL,
                          start_date DATETIME(6) DEFAULT NULL,
                          status ENUM('ACTIVE','ARCHIVED','CANCELLED','COMPLETED','ON_HOLD','PLANNING') NOT NULL,
                          task_count INT DEFAULT NULL,
                          is_template BIT(1) DEFAULT NULL,
                          updated_at DATETIME(6) DEFAULT NULL,
                          visibility ENUM('PRIVATE','PUBLIC','SECRET') NOT NULL,
                          PRIMARY KEY (id),
                          UNIQUE KEY UKcxqk67qijm09gpgig8a997mb0 (slug),
                          KEY idx_project_org_id (org_id),
                          KEY idx_project_status (status),
                          KEY idx_project_slug (slug),
                          KEY idx_project_created_by (created_by),
                          CONSTRAINT fk_project_org FOREIGN KEY (org_id) REFERENCES organizations(id),
                          CONSTRAINT fk_project_created_by FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;